inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.2

Documentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120

Style/FileName:
  Exclude:
    - bin/scss-lint

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/features/*'
    - 'spec/requests/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/features/*'
    - 'spec/requests/*'

Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'