AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/FileName:
  Exclude:
    - bin/scss-lint

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/features/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/features/*'
