sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - tmp/cache/assets/test
node_js:
- '0.10'
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
before_script:
- npm install
- bundle exec rake db:create db:migrate RAILS_ENV=test
notifications:
  slack:
    secure: NMsB6mM98XgtD3eeTgXfebPyehvVWJamU6ytl3l6/CApLNLKIEYjpaiPsxCLvIncEF24EqrqVOfgXX2QBWMEf1Q2bGiOhrihHzzL/Jv7mzFV7M6uv/geHeHO39Iefl7IKCIVJtkda7GGS5xBVY4Yyxxw876Tdp2dSqnvNIXnfI+EheFSlzzL03p04g5oFHLh8NPcr80G3d9AGtNibu2FxNPi5arD3+aLMg1/ZDPXLu7vxBvgvTYIq1czzhn2XjcmaJF1mM+LLKM1+NdwutViGui3uzbA1+QZ/khymQ6oqslbgvJKSL2CqIDXCu6rLvM45dM2tSvnfvKEb3Z1B4hfNkGMBH3JrpvsHFJA4PA6TzOVZP/wVXClDlMu5Tfj8uQ53pKFUTyYZoP86Sst47mcUWCgai/xYAdXaCuoPowM28M5ADyD5JEM49OSQuLnWOR/s447QCtEmfB3giztSmzdLpvbAG7KQ6eaYb0Aeh5qyjUcHk7mmt031qLjcCcBT6Irh4MJUpXkXYM94NYVkt9fI7d1+MkibkRD2YftzrLhAqNMvfl4D3CUYsrEnimrtJEIc/ouQmkQOoQaa2SxiGTEQHl7wPlojnMeKiOVtLCednqWH7e+560fiA6IluioeE3BHg7NC4V3HQMGSzlTnb1W5IkXlRzHNOqL6Z8NOyFzSqQ=
