sudo: false
language: ruby
services:
- redis-server
cache:
  bundler: true
  directories:
  - tmp/cache/assets/test
  - $HOME/.nvm
  - $HOME/.yarn-cache
  - $HOME/yarn-bin
node_js:
- '0.10'
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
before_script:
- nvm install 4
- nvm use 4
- wget https://yarnpkg.com/latest.tar.gz
- mkdir -p $HOME/yarn-bin
- tar zxvf latest.tar.gz -C $HOME/yarn-bin > /dev/null 2>&1
- env
- export PATH="$PATH:$HOME/yarn-bin/dist/bin"
# - $HOME/yarn-bin/dist/bin/yarn
- yarn
- gem update --system
- bundle exec rake db:create db:migrate RAILS_ENV=test
notifications:
  slack:
    secure: izFI8CV1BAc5Sk08/q84YijolWAY2Zm3JA4RPyilwjzfrro5v2lOM9rEX32W1fgPDu7hWq1bmqYcgxhVI+ecu2RFkI0iQklgNSe256HN7AKqRtSgtVx+3L6w8B9tBCJJ9wfj0lur/8x6oh8UwH8jExJmqtJbL3rxIq+O9N0/nJdf4jXR9vPHfFtprZwExQQTDQccqXkfyE+BqYRsFjoa/jL0utZlLt5kn8ErQPW/lDiSFvOA9OKk5o2ihQrndxkhAhZX6GbKp2aBP3xkom37aQZRyXsKIMXCz16+0IGOsTrW32j3lwLjsesb308Bp01e4q4ssp3a+2k5Hs2CKs0++b9Bb4GLpEl6Q63TGewUqK9/TXjvp7IWx5SOTQbktB5YLL6WmfR+j7MfD52VrEIHahEgJUwQQ+2+EG9MP0O8Qbs4Gek1FgGtpN7+rUS9WpOUIiGEjN7+uGd+PHTgSL7gf0kqrhtQcDHkP8KfI7KOrB1O0gO4DmdHNfJ184MXKEFlh7ULKtX08i8iB5GMVGQqsCuI7lfgR/P+u/SlIbPVu/aRoXpzo4e18UVpjBl9fR5mk6vroXqiR/5v4sHByFp5wn/QwvGszXjZcgmqTtZ7tyGGoq1IS6QdPr1Y0D/mBZT/O4N7QzG7fugPXwKOIfiktPooGt6CSVca5SHa13OkBrk=
